version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
        - 3306:3306
    volumes:
        - /home/vagner/Docker/volumes/mysql:/var/lib/mysql
    networks:
        - mysql-network

  adminer:
    image: adminer
    container_name: mysql_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-network

networks: 
    mysql-network:
        driver: bridge
